STOCK_PART_DATA = {
   "result" : {
      "paging" : {
         "items_per_page" : 25,
         "total_pages" : 111,
         "page_number" : 1,
         "next_page_number" : 2,
         "previous_page_number" : 1,
         "total_items" : 2766
      },
      "items" : [
         {
            "quantity_available_for_shop" : 652,
            "sku_id" : "0DDDA64E-371F-11E6-BF52-F30B71C3C4B9",
            "badge" : None,
            "price_10" : "0.2593",
            "price_100" : "0.2075",
            "owner_carton_label" : None,
            "box_insert" : 0,
            "use_insert_with_parts_boxes" : None,
            "on_sale" : 0,
            "description" : "An 11\" by 11\" plastic resealable baggie.  Perfect for all your part or card holding needs.",
            "size_in_mm" : 0,
            "date_updated" : "2023-10-23 15:33:58",
            "original_price_10" : "0.2593",
            "use_insert_with_boxes" : None,
            "original_price" : "0.3525",
            "interior_height" : 0,
            "date_created" : "2016-06-20 19:41:59",
            "last_price_change" : "2021-10-04 16:05:42",
            "departments" : [
               "parts"
            ],
            "photo_size" : "300x300",
            "sale_price" : 0,
            "discontinued" : 0,
            "height" : 12,
            "virtual" : 0,
            "uri_part" : "11-x-11-baggies",
            "public" : 1,
            "weight" : 0.323,
            "category" : "Bags",
            "original_price_1000" : "0.1355",
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/9AA02B16-C43E-11ED-8361-9686DB6D3EB3.png",
            "supplies" : 1,
            "usable_in_games" : 1,
            "units_per_carton" : 1,
            "id" : "0DDAE2A6-371F-11E6-BF52-F30B71C3C4B9",
            "family" : "Plastic Baggies",
            "shop_uri" : "/parts/11-x-11-baggies",
            "number_of_sides" : 0,
            "made_on_demand" : 0,
            "low_volume" : 0,
            "color" : "Clear",
            "material" : "Plastic",
            "youtube_video_id" : "",
            "name" : "11 X 11 Baggies",
            "quantity" : 1002,
            "object_type" : "part",
            "object_name" : "Part",
            "for_resale" : 1,
            "box" : 0,
            "depth" : 0.01,
            "width" : 11,
            "upc" : None,
            "sale_ends" : "2016-06-20 19:41:59",
            "quantity_available_for_games" : 952,
            "spare_parts" : 0,
            "keywords" : "Bags, Baggies, Plastic, Ziploc, Clear, Plastic, container, tiptop",
            "owner_sku" : None,
            "price" : "0.3525",
            "has_extraimages" : 1,
            "price_1000" : "0.1355",
            "interior_width" : 0,
            "interior_depth" : 0,
            "vintage" : 0,
            "made_in_the_usa" : 0,
            "is_3d_printed" : 0,
            "original_price_100" : "0.2075",
            "date_published" : "2017-07-12 18:32:24"
         },
         {
            "upc" : None,
            "width" : 1.574803,
            "depth" : 0.590551,
            "price" : "1.0655",
            "has_extraimages" : 1,
            "keywords" : "first, lettering, type, player token",
            "owner_sku" : None,
            "spare_parts" : 0,
            "quantity_available_for_games" : 80000,
            "sale_ends" : "2021-12-13 18:41:48",
            "interior_width" : 0,
            "price_1000" : "0.4920",
            "date_published" : "2021-12-13 18:41:53",
            "original_price_100" : "0.6828",
            "is_3d_printed" : 1,
            "made_in_the_usa" : 1,
            "interior_depth" : 0,
            "vintage" : 0,
            "color" : "Gold",
            "low_volume" : 0,
            "made_on_demand" : 1,
            "youtube_video_id" : None,
            "name" : "1st",
            "material" : "Plastic",
            "object_name" : "Part",
            "object_type" : "part",
            "quantity" : 176,
            "box" : 0,
            "for_resale" : 1,
            "uri_part" : "1st",
            "public" : 1,
            "virtual" : 0,
            "height" : 1.535433,
            "discontinued" : 0,
            "original_price_1000" : "0.4920",
            "category" : "Tokens",
            "weight" : 0.2142,
            "family" : "First Player Tokens",
            "id" : "547241F0-5C44-11EC-9FE2-292A68FE145E",
            "units_per_carton" : 1,
            "usable_in_games" : 1,
            "supplies" : 0,
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/67F0DE98-61E0-11EC-BA8E-D08503B57022.png",
            "number_of_sides" : 0,
            "shop_uri" : "/parts/1st",
            "price_10" : "0.8535",
            "price_100" : "0.6828",
            "badge" : None,
            "sku_id" : "548B44CA-5C44-11EC-9FE2-292A68FE145E",
            "quantity_available_for_shop" : 80000,
            "use_insert_with_boxes" : None,
            "date_updated" : "2023-10-23 08:50:18",
            "original_price_10" : "0.8535",
            "description" : "Heavy lettering that spell out \"1st\". An unambiguous first player token.",
            "size_in_mm" : 0,
            "on_sale" : 0,
            "use_insert_with_parts_boxes" : None,
            "owner_carton_label" : None,
            "box_insert" : 0,
            "date_created" : "2021-12-13 18:41:48",
            "interior_height" : 0,
            "original_price" : "1.0655",
            "sale_price" : 0,
            "photo_size" : "300x300",
            "departments" : [
               "parts"
            ],
            "last_price_change" : "2023-03-14 21:41:13"
         },
         {
            "supplies" : 1,
            "usable_in_games" : 1,
            "id" : "E565ABBA-9A04-11E0-AACC-432941C43697",
            "units_per_carton" : 1,
            "family" : "Plastic Baggies",
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/1479D068-C43F-11ED-8361-A78BDB6D3EB3.png",
            "number_of_sides" : 0,
            "shop_uri" : "/parts/3-x-4-baggies",
            "virtual" : 0,
            "public" : 1,
            "uri_part" : "3-x-4-baggies",
            "discontinued" : 0,
            "height" : 5,
            "weight" : 0.0416,
            "category" : "Bags",
            "original_price_1000" : "0.0327",
            "original_price" : "0.1469",
            "interior_height" : 0,
            "date_created" : "2011-06-18 23:44:24",
            "photo_size" : "300x300",
            "sale_price" : 0,
            "last_price_change" : "2021-10-04 16:06:30",
            "departments" : [
               "parts"
            ],
            "price_100" : "0.0704",
            "price_10" : "0.0881",
            "quantity_available_for_shop" : 0,
            "badge" : None,
            "sku_id" : "E565B51A-9A04-11E0-AACC-432941C43697",
            "description" : "A 3\" by 4\" plastic resealable baggie.  Perfect for all your part or card holding needs.",
            "size_in_mm" : 0,
            "date_updated" : "2023-10-23 15:18:11",
            "original_price_10" : "0.0881",
            "use_insert_with_boxes" : None,
            "box_insert" : 0,
            "owner_carton_label" : None,
            "use_insert_with_parts_boxes" : None,
            "on_sale" : 0,
            "interior_width" : 0,
            "price_1000" : "0.0327",
            "original_price_100" : "0.0704",
            "date_published" : "2017-07-13 16:24:34",
            "interior_depth" : 0,
            "made_in_the_usa" : 0,
            "vintage" : 0,
            "is_3d_printed" : 0,
            "width" : 3,
            "upc" : None,
            "depth" : 0.01,
            "owner_sku" : None,
            "keywords" : "Bags, Baggies, Plastic, Ziploc, Clear, Plastic, container, ziptop, resealable, reusable",
            "price" : "0.1469",
            "has_extraimages" : 1,
            "sale_ends" : "2013-01-01 00:00:00",
            "quantity_available_for_games" : 300,
            "spare_parts" : 0,
            "object_type" : "part",
            "object_name" : "Part",
            "quantity" : 400,
            "box" : 0,
            "for_resale" : 1,
            "low_volume" : 0,
            "color" : "Clear",
            "made_on_demand" : 0,
            "youtube_video_id" : "",
            "name" : "3 X 4 Baggies",
            "material" : "Plastic"
         },
         {
            "price_1000" : "0.0642",
            "interior_width" : 0,
            "is_3d_printed" : 0,
            "made_in_the_usa" : 0,
            "interior_depth" : 0,
            "vintage" : 0,
            "date_published" : "2017-07-13 22:31:12",
            "original_price_100" : "0.1124",
            "depth" : 0.05,
            "upc" : None,
            "width" : 4,
            "spare_parts" : 0,
            "quantity_available_for_games" : 1050,
            "sale_ends" : "2016-08-11 17:59:16",
            "has_extraimages" : 1,
            "price" : "0.2099",
            "owner_sku" : None,
            "keywords" : "Bags, Baggies, Plastic, Ziploc, Clear, Plastic, container, ziptop, resealable, reusable",
            "quantity" : 1100,
            "object_name" : "Part",
            "object_type" : "part",
            "for_resale" : 1,
            "box" : 0,
            "made_on_demand" : 0,
            "color" : "Clear",
            "low_volume" : 0,
            "material" : "Plastic",
            "name" : "4 X 10 Baggies",
            "youtube_video_id" : "",
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/0C7B124A-C4D6-11ED-A4D8-AE945FA0F72B.png",
            "family" : "Plastic Baggies",
            "id" : "51F56B04-5FED-11E6-B743-AB73326D0F3E",
            "units_per_carton" : 1,
            "usable_in_games" : 1,
            "supplies" : 1,
            "shop_uri" : "/parts/4-x-10-baggies",
            "number_of_sides" : 0,
            "height" : 11,
            "discontinued" : 0,
            "public" : 1,
            "uri_part" : "4-x-10-baggies",
            "virtual" : 0,
            "original_price_1000" : "0.0642",
            "category" : "Bags",
            "weight" : 0.11,
            "date_created" : "2016-08-11 17:59:16",
            "interior_height" : 0,
            "original_price" : "0.2099",
            "departments" : [
               "parts"
            ],
            "last_price_change" : "2021-10-04 16:06:09",
            "sale_price" : 0,
            "photo_size" : "300x300",
            "sku_id" : "51F85922-5FED-11E6-B743-AB73326D0F3E",
            "badge" : None,
            "quantity_available_for_shop" : 750,
            "price_10" : "0.1405",
            "price_100" : "0.1124",
            "use_insert_with_parts_boxes" : None,
            "on_sale" : 0,
            "owner_carton_label" : None,
            "box_insert" : 0,
            "use_insert_with_boxes" : None,
            "original_price_10" : "0.1405",
            "date_updated" : "2023-10-19 21:01:33",
            "description" : "A 4\" by 10\" plastic resealable baggie.  Perfect for all your part or card holding needs.",
            "size_in_mm" : 0
         },
         {
            "is_3d_printed" : 0,
            "made_in_the_usa" : 0,
            "interior_depth" : 0,
            "vintage" : 0,
            "original_price_100" : "0.0771",
            "date_published" : "2017-07-13 22:25:17",
            "price_1000" : "0.0377",
            "interior_width" : 0,
            "quantity_available_for_games" : 9377,
            "sale_ends" : "2013-01-01 00:00:00",
            "spare_parts" : 0,
            "keywords" : "Bags, Baggies, Plastic, Ziploc, Clear, Plastic, container, ziptop, resealable, reusable",
            "owner_sku" : None,
            "price" : "0.1569",
            "has_extraimages" : 1,
            "depth" : 0.01,
            "width" : 4,
            "upc" : None,
            "for_resale" : 1,
            "box" : 0,
            "quantity" : 9577,
            "object_type" : "part",
            "object_name" : "Part",
            "material" : "Plastic",
            "youtube_video_id" : "",
            "name" : "4 X 5 Baggies",
            "made_on_demand" : 0,
            "color" : "Clear",
            "low_volume" : 0,
            "shop_uri" : "/parts/4-x-5-baggies",
            "number_of_sides" : 0,
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/EB1FB2FA-C43E-11ED-85BE-09BA5FA0F72B.png",
            "units_per_carton" : 1,
            "id" : "A8D6D960-1700-11E2-A551-B0F21C5FFC75",
            "family" : "Plastic Baggies",
            "supplies" : 1,
            "usable_in_games" : 1,
            "category" : "Bags",
            "original_price_1000" : "0.0377",
            "weight" : 0.056,
            "height" : 5.75,
            "discontinued" : 0,
            "public" : 1,
            "uri_part" : "4-x-5-baggies",
            "virtual" : 0,
            "departments" : [
               "parts"
            ],
            "last_price_change" : "2021-10-04 16:06:31",
            "photo_size" : "300x300",
            "sale_price" : 0,
            "interior_height" : 0,
            "date_created" : "2012-10-15 19:43:57",
            "original_price" : "0.1569",
            "on_sale" : 0,
            "use_insert_with_parts_boxes" : None,
            "owner_carton_label" : None,
            "box_insert" : 0,
            "use_insert_with_boxes" : None,
            "size_in_mm" : 0,
            "description" : "A 4\" by 5\" plastic resealable baggie.  Perfect for all your part or card holding needs.",
            "original_price_10" : "0.0963",
            "date_updated" : "2023-10-23 12:49:26",
            "quantity_available_for_shop" : 8177,
            "sku_id" : "A8D6F04E-1700-11E2-A551-B0F21C5FFC75",
            "badge" : None,
            "price_10" : "0.0963",
            "price_100" : "0.0771"
         },
         {
            "on_sale" : 0,
            "use_insert_with_parts_boxes" : None,
            "box_insert" : 0,
            "owner_carton_label" : None,
            "use_insert_with_boxes" : None,
            "description" : "A 4\" by 6\" plastic resealable baggie.  Perfect for all your part or card holding needs.",
            "size_in_mm" : 0,
            "original_price_10" : "0.1019",
            "date_updated" : "2023-10-23 06:46:56",
            "quantity_available_for_shop" : 2300,
            "badge" : None,
            "sku_id" : "7BDB60D8-7552-11E2-8CD2-A500A0042459",
            "price_100" : "0.0815",
            "price_10" : "0.1019",
            "departments" : [
               "parts"
            ],
            "last_price_change" : "2021-10-04 16:06:33",
            "photo_size" : "300x300",
            "sale_price" : 0,
            "date_created" : "2013-02-12 20:26:30",
            "interior_height" : 0,
            "original_price" : "0.1635",
            "category" : "Bags",
            "original_price_1000" : "0.0410",
            "weight" : 0.065,
            "height" : 6.75,
            "discontinued" : 0,
            "public" : 1,
            "uri_part" : "4-x-6-baggies",
            "virtual" : 0,
            "shop_uri" : "/parts/4-x-6-baggies",
            "number_of_sides" : 0,
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/BAB10038-C43E-11ED-8361-EE87DB6D3EB3.png",
            "id" : "7BDB279E-7552-11E2-8CD2-A500A0042459",
            "units_per_carton" : 1,
            "family" : "Plastic Baggies",
            "supplies" : 1,
            "usable_in_games" : 1,
            "material" : "Plastic",
            "name" : "4 X 6 Baggies",
            "youtube_video_id" : "",
            "made_on_demand" : 0,
            "color" : "Clear",
            "low_volume" : 0,
            "for_resale" : 1,
            "box" : 0,
            "quantity" : 3000,
            "object_type" : "part",
            "object_name" : "Part",
            "quantity_available_for_games" : 2900,
            "sale_ends" : "2013-01-01 00:00:00",
            "spare_parts" : 0,
            "owner_sku" : None,
            "keywords" : "Bags, Baggies, Plastic, Ziploc, Clear, Plastic, container, ziptop, resealable, reusable",
            "price" : "0.1635",
            "has_extraimages" : 1,
            "depth" : 0.01,
            "width" : 4,
            "upc" : None,
            "is_3d_printed" : 0,
            "vintage" : 0,
            "interior_depth" : 0,
            "made_in_the_usa" : 0,
            "original_price_100" : "0.0815",
            "date_published" : "2017-07-13 22:31:08",
            "price_1000" : "0.0410",
            "interior_width" : 0
         },
         {
            "quantity_available_for_shop" : 1335,
            "badge" : None,
            "sku_id" : "8DD102FC-1701-11E2-AF9A-B0F21C5FFC75",
            "price_100" : "0.0925",
            "price_10" : "0.1157",
            "on_sale" : 0,
            "use_insert_with_parts_boxes" : None,
            "owner_carton_label" : None,
            "box_insert" : 0,
            "use_insert_with_boxes" : None,
            "description" : "A 5\" by 5\" plastic resealable baggie.  Perfect for all your part or card holding needs.",
            "size_in_mm" : 0,
            "original_price_10" : "0.1157",
            "date_updated" : "2023-10-23 15:17:24",
            "date_created" : "2012-10-15 19:50:21",
            "interior_height" : 0,
            "original_price" : "0.1801",
            "departments" : [
               "parts"
            ],
            "last_price_change" : "2021-10-04 16:06:34",
            "photo_size" : "300x300",
            "sale_price" : 0,
            "height" : 5.75,
            "discontinued" : 0,
            "public" : 1,
            "uri_part" : "5-x-5-baggies",
            "virtual" : 0,
            "category" : "Bags",
            "original_price_1000" : "0.0493",
            "weight" : 0.073,
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/E2B80B62-C43E-11ED-8361-C189DB6D3EB3.png",
            "id" : "8DD0DD90-1701-11E2-AF9A-B0F21C5FFC75",
            "units_per_carton" : 1,
            "family" : "Plastic Baggies",
            "supplies" : 1,
            "usable_in_games" : 1,
            "shop_uri" : "/parts/5-x-5-baggies",
            "number_of_sides" : 0,
            "made_on_demand" : 0,
            "color" : "Clear",
            "low_volume" : 0,
            "material" : "Plastic",
            "youtube_video_id" : "",
            "name" : "5 X 5 Baggies",
            "quantity" : 2035,
            "object_type" : "part",
            "object_name" : "Part",
            "for_resale" : 1,
            "box" : 0,
            "depth" : 0.01,
            "width" : 5,
            "upc" : None,
            "sale_ends" : "2013-01-01 00:00:00",
            "quantity_available_for_games" : 1935,
            "spare_parts" : 0,
            "owner_sku" : None,
            "keywords" : "Bags, Baggies, Plastic, Ziploc, Clear, Plastic, container, ziptop, resealable, reusable",
            "has_extraimages" : 1,
            "price" : "0.1801",
            "price_1000" : "0.0493",
            "interior_width" : 0,
            "is_3d_printed" : 0,
            "vintage" : 0,
            "interior_depth" : 0,
            "made_in_the_usa" : 0,
            "original_price_100" : "0.0925",
            "date_published" : "2017-07-13 22:31:22"
         },
         {
            "quantity" : 4000,
            "object_type" : "part",
            "object_name" : "Part",
            "for_resale" : 1,
            "box" : 0,
            "made_on_demand" : 0,
            "low_volume" : 0,
            "color" : "Clear",
            "material" : "Plastic",
            "youtube_video_id" : "",
            "name" : "5 X 7 Baggies",
            "price_1000" : "0.0526",
            "interior_width" : 0,
            "made_in_the_usa" : 0,
            "interior_depth" : 0,
            "vintage" : 0,
            "is_3d_printed" : 0,
            "original_price_100" : "0.0970",
            "date_published" : "2017-07-13 04:50:30",
            "depth" : 0.01,
            "width" : 5,
            "upc" : None,
            "quantity_available_for_games" : 3850,
            "sale_ends" : "2013-01-01 00:00:00",
            "spare_parts" : 0,
            "owner_sku" : None,
            "keywords" : "Bags, Baggies, Plastic, Ziploc, Clear, Plastic, container, ziptop, resealable, reusable",
            "price" : "0.1867",
            "has_extraimages" : 1,
            "original_price" : "0.1867",
            "date_created" : "2012-10-15 19:53:15",
            "interior_height" : 0,
            "last_price_change" : "2021-10-04 16:06:34",
            "departments" : [
               "parts"
            ],
            "photo_size" : "300x300",
            "sale_price" : 0,
            "quantity_available_for_shop" : 2950,
            "sku_id" : "F58FDB98-1701-11E2-B442-B0F21C5FFC75",
            "badge" : None,
            "price_10" : "0.1212",
            "price_100" : "0.0970",
            "box_insert" : 0,
            "owner_carton_label" : None,
            "on_sale" : 0,
            "use_insert_with_parts_boxes" : None,
            "size_in_mm" : 0,
            "description" : "A 5\" by 7\" plastic resealable baggie.  Perfect for all your part or card holding needs.",
            "original_price_10" : "0.1212",
            "date_updated" : "2023-10-21 05:16:55",
            "use_insert_with_boxes" : None,
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/2222AB68-C43F-11ED-85BE-8DBC5FA0F72B.png",
            "supplies" : 1,
            "usable_in_games" : 1,
            "units_per_carton" : 1,
            "id" : "F58FA718-1701-11E2-B442-B0F21C5FFC75",
            "family" : "Plastic Baggies",
            "shop_uri" : "/parts/5-x-7-baggies",
            "number_of_sides" : 0,
            "discontinued" : 0,
            "height" : 8,
            "virtual" : 0,
            "uri_part" : "5-x-7-baggies",
            "public" : 1,
            "weight" : 0.1035,
            "category" : "Bags",
            "original_price_1000" : "0.0526"
         },
         {
            "virtual" : 0,
            "uri_part" : "6-x-10-baggies",
            "public" : 1,
            "discontinued" : 0,
            "height" : 10.75,
            "weight" : 0.16,
            "original_price_1000" : "0.0675",
            "category" : "Bags",
            "usable_in_games" : 1,
            "supplies" : 1,
            "family" : "Plastic Baggies",
            "units_per_carton" : 1,
            "id" : "C14C29E8-3A93-11E3-AFFE-50F7DCC3CC15",
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/03D81DBE-C43F-11ED-8361-118BDB6D3EB3.png",
            "number_of_sides" : 0,
            "shop_uri" : "/parts/6-x-10-baggies",
            "price_10" : "0.1461",
            "price_100" : "0.1169",
            "sku_id" : "C14C6322-3A93-11E3-AFFE-50F7DCC3CC15",
            "badge" : None,
            "quantity_available_for_shop" : 890,
            "date_updated" : "2023-10-19 21:02:32",
            "original_price_10" : "0.1461",
            "description" : "A 6\" by 10\" plastic resealable baggie.  Perfect for all your part or card holding needs.",
            "size_in_mm" : 0,
            "use_insert_with_boxes" : None,
            "owner_carton_label" : None,
            "box_insert" : 0,
            "on_sale" : 0,
            "use_insert_with_parts_boxes" : None,
            "original_price" : "0.2165",
            "date_created" : "2013-10-21 21:00:02",
            "interior_height" : 0,
            "sale_price" : 0,
            "photo_size" : "300x300",
            "last_price_change" : "2021-10-04 16:06:35",
            "departments" : [
               "parts"
            ],
            "upc" : None,
            "width" : 6,
            "depth" : 0.01,
            "price" : "0.2165",
            "has_extraimages" : 1,
            "keywords" : "Bags, Baggies, Plastic, Ziploc, Clear, Plastic, container, ziptop, resealable, reusable",
            "owner_sku" : None,
            "spare_parts" : 0,
            "quantity_available_for_games" : 1070,
            "sale_ends" : "2013-10-21 21:00:02",
            "interior_width" : 0,
            "price_1000" : "0.0675",
            "date_published" : "2017-07-11 15:45:07",
            "original_price_100" : "0.1169",
            "vintage" : 0,
            "interior_depth" : 0,
            "made_in_the_usa" : 0,
            "is_3d_printed" : 0,
            "low_volume" : 0,
            "color" : "Clear",
            "made_on_demand" : 0,
            "name" : "6 X 10 Baggies",
            "youtube_video_id" : "",
            "material" : "Plastic",
            "object_name" : "Part",
            "object_type" : "part",
            "quantity" : 1100,
            "box" : 0,
            "for_resale" : 1
         },
         {
            "box_insert" : 0,
            "owner_carton_label" : None,
            "use_insert_with_parts_boxes" : None,
            "on_sale" : 0,
            "size_in_mm" : 0,
            "description" : "A 7\" by 12\" plastic resealable baggie.  Perfect for all your part or card holding needs.",
            "original_price_10" : "0.1958",
            "date_updated" : "2023-10-23 06:06:08",
            "use_insert_with_boxes" : None,
            "quantity_available_for_shop" : 890,
            "sku_id" : "B31252F4-6084-11E4-852A-308EED7A9241",
            "badge" : None,
            "price_100" : "0.1566",
            "price_10" : "0.1958",
            "last_price_change" : "2021-10-04 16:06:37",
            "departments" : [
               "parts"
            ],
            "photo_size" : "300x300",
            "sale_price" : 0,
            "original_price" : "0.2762",
            "date_created" : "2014-10-30 22:32:58",
            "interior_height" : 0,
            "weight" : 0.225,
            "category" : "Bags",
            "original_price_1000" : "0.0974",
            "discontinued" : 0,
            "height" : 12,
            "virtual" : 0,
            "uri_part" : "7-x-12-baggies",
            "public" : 1,
            "shop_uri" : "/parts/7-x-12-baggies",
            "number_of_sides" : 0,
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/F8011176-C43E-11ED-8361-0F8BDB6D3EB3.png",
            "supplies" : 1,
            "usable_in_games" : 1,
            "units_per_carton" : 1,
            "id" : "B3121F5A-6084-11E4-852A-308EED7A9241",
            "family" : "Plastic Baggies",
            "material" : "Plastic",
            "youtube_video_id" : "",
            "name" : "7 X 12 Baggies",
            "made_on_demand" : 0,
            "low_volume" : 0,
            "color" : "Clear",
            "for_resale" : 1,
            "box" : 0,
            "quantity" : 1100,
            "object_type" : "part",
            "object_name" : "Part",
            "quantity_available_for_games" : 1070,
            "sale_ends" : "2014-10-30 22:32:58",
            "spare_parts" : 0,
            "keywords" : "Bags, Baggies, Plastic, Ziploc, Clear, Plastic, container, ziptop, resealable, reusable",
            "owner_sku" : None,
            "has_extraimages" : 1,
            "price" : "0.2762",
            "depth" : 0.01,
            "width" : 7,
            "upc" : None,
            "interior_depth" : 0,
            "vintage" : 0,
            "made_in_the_usa" : 0,
            "is_3d_printed" : 0,
            "original_price_100" : "0.1566",
            "date_published" : "2017-07-13 22:12:22",
            "price_1000" : "0.0974",
            "interior_width" : 0
         },
         {
            "discontinued" : 0,
            "height" : 12,
            "virtual" : 0,
            "uri_part" : "9-x-12-baggies",
            "public" : 1,
            "weight" : 0.256,
            "original_price_1000" : "0.0858",
            "category" : "Bags",
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/3555AB68-C43F-11ED-B904-ABFB00937027.png",
            "usable_in_games" : 1,
            "supplies" : 1,
            "family" : "Plastic Baggies",
            "id" : "FAEBD286-10AE-11E6-AD06-9AD083317F59",
            "units_per_carton" : 1,
            "shop_uri" : "/parts/9-x-12-baggies",
            "number_of_sides" : 0,
            "badge" : None,
            "sku_id" : "FAEBE46A-10AE-11E6-AD06-9AD083317F59",
            "quantity_available_for_shop" : 1050,
            "price_100" : "0.1412",
            "price_10" : "0.1765",
            "box_insert" : 0,
            "owner_carton_label" : None,
            "on_sale" : 0,
            "use_insert_with_parts_boxes" : None,
            "date_updated" : "2023-10-19 21:02:52",
            "original_price_10" : "0.1765",
            "description" : "A 9\" by 12\" plastic resealable baggie.  Perfect for all your part or card holding needs.",
            "size_in_mm" : 0,
            "use_insert_with_boxes" : None,
            "original_price" : "0.2530",
            "date_created" : "2016-05-02 21:44:00",
            "interior_height" : 0,
            "last_price_change" : "2021-10-04 16:06:18",
            "departments" : [
               "parts"
            ],
            "sale_price" : 0,
            "photo_size" : "300x300",
            "depth" : 0.01,
            "upc" : None,
            "width" : 9,
            "spare_parts" : 0,
            "quantity_available_for_games" : 1350,
            "sale_ends" : "2016-05-02 21:44:00",
            "has_extraimages" : 1,
            "price" : "0.2530",
            "keywords" : "Bags, Baggies, Plastic, Ziploc, Clear, Plastic, container, ziptop, resealable, reusable",
            "owner_sku" : None,
            "price_1000" : "0.0858",
            "interior_width" : 0,
            "interior_depth" : 0,
            "made_in_the_usa" : 0,
            "vintage" : 0,
            "is_3d_printed" : 0,
            "date_published" : "2017-07-11 14:42:57",
            "original_price_100" : "0.1412",
            "made_on_demand" : 0,
            "low_volume" : 0,
            "color" : "Clear",
            "material" : "Plastic",
            "youtube_video_id" : "",
            "name" : "9 X 12 Baggies",
            "quantity" : 1400,
            "object_name" : "Part",
            "object_type" : "part",
            "for_resale" : 1,
            "box" : 0
         },
         {
            "spare_parts" : 0,
            "sale_ends" : "2023-01-30 18:59:14",
            "quantity_available_for_games" : 5668,
            "has_extraimages" : 1,
            "price" : "0.2265",
            "keywords" : "nut, tree, squirrel, oak, oaknut, Quercus, lithocarpus, fagaceae, seed, akerne, acharn, akran, fruit, achornes, forest, nuts, birds, rodents, tannins, cache, chestnuts, waymark, ",
            "owner_sku" : None,
            "depth" : 0.3,
            "upc" : None,
            "width" : 0.56,
            "vintage" : 0,
            "interior_depth" : 0,
            "made_in_the_usa" : 0,
            "is_3d_printed" : 0,
            "date_published" : "2023-01-30 18:59:19",
            "original_price_100" : "0.1235",
            "price_1000" : "0.0725",
            "interior_width" : 0,
            "material" : "Plastic",
            "youtube_video_id" : None,
            "name" : "Acorn, Brown",
            "made_on_demand" : 0,
            "low_volume" : 1,
            "color" : "Brown",
            "for_resale" : 1,
            "box" : 0,
            "quantity" : 5669,
            "object_name" : "Part",
            "object_type" : "part",
            "weight" : 0.0269,
            "original_price_1000" : "0.0725",
            "category" : "Tokens",
            "discontinued" : 0,
            "height" : 0.7,
            "virtual" : 0,
            "public" : 1,
            "uri_part" : "acorn-brown",
            "shop_uri" : "/parts/acorn-brown",
            "number_of_sides" : 0,
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/1B9DAF0C-A24A-11ED-8876-1F792A49FC29.png",
            "usable_in_games" : 1,
            "supplies" : 0,
            "family" : "Nuts",
            "units_per_carton" : 1,
            "id" : "301AEFF6-A0D0-11ED-8DB7-1D472A49FC29",
            "box_insert" : 0,
            "owner_carton_label" : None,
            "on_sale" : 0,
            "use_insert_with_parts_boxes" : None,
            "original_price_10" : "0.1544",
            "date_updated" : "2023-10-20 15:21:14",
            "description" : "A small brown acorn great for any games with squirrels or trees",
            "size_in_mm" : 18,
            "use_insert_with_boxes" : None,
            "badge" : "Low Volume",
            "sku_id" : "30336EDC-A0D0-11ED-8DB7-1D472A49FC29",
            "quantity_available_for_shop" : 5668,
            "price_100" : "0.1235",
            "price_10" : "0.1544",
            "last_price_change" : "2023-01-30 19:04:22",
            "departments" : [
               "parts"
            ],
            "sale_price" : 0,
            "photo_size" : "300x300",
            "original_price" : "0.2265",
            "date_created" : "2023-01-30 18:59:14",
            "interior_height" : 0
         },
         {
            "last_price_change" : "2023-01-30 18:58:27",
            "departments" : [
               "parts"
            ],
            "sale_price" : 0,
            "photo_size" : "300x300",
            "original_price" : "0.2265",
            "interior_height" : 0,
            "date_created" : "2023-01-30 18:44:27",
            "box_insert" : 0,
            "owner_carton_label" : None,
            "use_insert_with_parts_boxes" : None,
            "on_sale" : 0,
            "date_updated" : "2023-10-20 02:09:46",
            "original_price_10" : "0.1544",
            "size_in_mm" : 18,
            "description" : "A small yellow acorn great for any games with squirrels or trees",
            "use_insert_with_boxes" : None,
            "badge" : "Low Volume",
            "sku_id" : "2002C816-A0CE-11ED-8DB7-E52C2A49FC29",
            "quantity_available_for_shop" : 1482,
            "price_100" : "0.1235",
            "price_10" : "0.1544",
            "shop_uri" : "/parts/acorn-yellow",
            "number_of_sides" : 0,
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/0BB773C0-A24A-11ED-8876-6E782A49FC29.png",
            "usable_in_games" : 1,
            "supplies" : 0,
            "family" : "Nuts",
            "id" : "1FFAF80C-A0CE-11ED-8DB7-E52C2A49FC29",
            "units_per_carton" : 1,
            "weight" : 0.0269,
            "original_price_1000" : "0.0725",
            "category" : "Tokens",
            "discontinued" : 0,
            "height" : 0.7,
            "virtual" : 0,
            "uri_part" : "acorn-yellow",
            "public" : 1,
            "for_resale" : 1,
            "box" : 0,
            "quantity" : 1483,
            "object_name" : "Part",
            "object_type" : "part",
            "material" : "Plastic",
            "name" : "Acorn, Yellow",
            "youtube_video_id" : None,
            "made_on_demand" : 0,
            "low_volume" : 1,
            "color" : "Yellow",
            "interior_depth" : 0,
            "vintage" : 0,
            "made_in_the_usa" : 0,
            "is_3d_printed" : 0,
            "date_published" : "2023-01-30 18:44:43",
            "original_price_100" : "0.1235",
            "price_1000" : "0.0725",
            "interior_width" : 0,
            "spare_parts" : 0,
            "quantity_available_for_games" : 1482,
            "sale_ends" : "2023-01-30 18:44:27",
            "price" : "0.2265",
            "has_extraimages" : 1,
            "keywords" : "nut, tree, squirrel, oak, oaknut, Quercus, lithocarpus, fagaceae, seed, akerne, acharn, akran, fruit, achornes, forest, nuts, birds, rodents, tannins, cache, chestnuts, waymark, ",
            "owner_sku" : None,
            "depth" : 0.3,
            "upc" : None,
            "width" : 0.56
         },
         {
            "interior_width" : 0,
            "price_1000" : "0.0626",
            "date_published" : "2018-02-28 18:06:22",
            "original_price_100" : "0.1102",
            "is_3d_printed" : 0,
            "made_in_the_usa" : 1,
            "interior_depth" : 0,
            "vintage" : 0,
            "upc" : None,
            "width" : 0.446,
            "depth" : 0.11,
            "has_extraimages" : 0,
            "price" : "0.2066",
            "keywords" : "track, train, railroad, railway, acrylic, token, rail, transport, tramway",
            "owner_sku" : None,
            "spare_parts" : 0,
            "quantity_available_for_games" : 80000,
            "sale_ends" : "2018-02-28 18:05:48",
            "object_name" : "Part",
            "object_type" : "part",
            "quantity" : -20,
            "box" : 0,
            "for_resale" : 1,
            "color" : "Black",
            "low_volume" : 0,
            "made_on_demand" : 1,
            "youtube_video_id" : "ImtUM7M0r2E",
            "name" : "Acrylic Train Track, Black",
            "material" : "Plastic",
            "family" : "Train Track",
            "units_per_carton" : 1,
            "id" : "01496AC4-1CB2-11E8-B093-2DEB93A6FE1D",
            "usable_in_games" : 1,
            "supplies" : 0,
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/04754D22-217F-11E8-8A2E-930394A6FE1D.png",
            "number_of_sides" : 0,
            "shop_uri" : "/parts/acrylic-train-track-black",
            "public" : 1,
            "uri_part" : "acrylic-train-track-black",
            "virtual" : 0,
            "height" : 1.26,
            "discontinued" : 0,
            "original_price_1000" : "0.0626",
            "category" : "Tokens",
            "weight" : 0.0288,
            "date_created" : "2018-02-28 18:05:48",
            "interior_height" : 0,
            "original_price" : "0.2066",
            "sale_price" : 0,
            "photo_size" : "300x300",
            "departments" : [
               "parts"
            ],
            "last_price_change" : "2018-08-22 15:24:12",
            "price_100" : "0.1102",
            "price_10" : "0.1378",
            "badge" : None,
            "sku_id" : "01578E60-1CB2-11E8-B093-2DEB93A6FE1D",
            "quantity_available_for_shop" : 80000,
            "use_insert_with_boxes" : None,
            "original_price_10" : "0.1378",
            "date_updated" : "2023-10-22 00:51:10",
            "size_in_mm" : 0,
            "description" : "An acrylic piece of train track.",
            "on_sale" : 0,
            "use_insert_with_parts_boxes" : None,
            "owner_carton_label" : None,
            "box_insert" : 0
         },
         {
            "color" : "Blue",
            "low_volume" : 0,
            "made_on_demand" : 1,
            "youtube_video_id" : "ImtUM7M0r2E",
            "name" : "Acrylic Train Track, Blue",
            "material" : "Plastic",
            "object_type" : "part",
            "object_name" : "Part",
            "quantity" : 328,
            "box" : 0,
            "for_resale" : 1,
            "width" : 0.446,
            "upc" : None,
            "depth" : 0.21,
            "owner_sku" : None,
            "keywords" : "track, train, railroad, railway, acrylic, token, rail, transport, tramway",
            "has_extraimages" : 0,
            "price" : "0.2066",
            "quantity_available_for_games" : 80000,
            "sale_ends" : "2018-03-12 18:47:15",
            "spare_parts" : 0,
            "interior_width" : 0,
            "price_1000" : "0.0626",
            "original_price_100" : "0.1102",
            "date_published" : "2018-03-12 20:54:32",
            "is_3d_printed" : 0,
            "vintage" : 0,
            "interior_depth" : 0,
            "made_in_the_usa" : 1,
            "price_10" : "0.1378",
            "price_100" : "0.1102",
            "quantity_available_for_shop" : 80000,
            "badge" : None,
            "sku_id" : "C8B5D62A-2625-11E8-8C8A-DEE7903967F6",
            "use_insert_with_boxes" : None,
            "description" : "An acrylic piece of train track.",
            "size_in_mm" : 0,
            "date_updated" : "2023-10-23 02:32:12",
            "original_price_10" : "0.1378",
            "use_insert_with_parts_boxes" : None,
            "on_sale" : 0,
            "owner_carton_label" : None,
            "box_insert" : 0,
            "interior_height" : 0,
            "date_created" : "2018-03-12 18:47:15",
            "original_price" : "0.2066",
            "photo_size" : "300x300",
            "sale_price" : 0,
            "departments" : [
               "parts"
            ],
            "last_price_change" : "2018-08-22 15:24:21",
            "public" : 1,
            "uri_part" : "acrylic-train-track-blue",
            "virtual" : 0,
            "height" : 1.26,
            "discontinued" : 0,
            "category" : "Tokens",
            "original_price_1000" : "0.0626",
            "weight" : 0.0304,
            "id" : "C8B386FE-2625-11E8-8C8A-DEE7903967F6",
            "units_per_carton" : 1,
            "family" : "Train Track",
            "supplies" : 0,
            "usable_in_games" : 1,
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/9EBA8C96-26DC-11E8-94C8-9D2BEB014BA6.png",
            "number_of_sides" : 0,
            "shop_uri" : "/parts/acrylic-train-track-blue"
         },
         {
            "quantity" : 316,
            "object_type" : "part",
            "object_name" : "Part",
            "for_resale" : 1,
            "box" : 0,
            "made_on_demand" : 1,
            "color" : "Green",
            "low_volume" : 0,
            "material" : "Plastic",
            "youtube_video_id" : "ImtUM7M0r2E",
            "name" : "Acrylic Train Track, Green",
            "price_1000" : "0.0626",
            "interior_width" : 0,
            "is_3d_printed" : 0,
            "interior_depth" : 0,
            "vintage" : 0,
            "made_in_the_usa" : 1,
            "original_price_100" : "0.1102",
            "date_published" : "2018-03-12 20:51:54",
            "depth" : 0.21,
            "width" : 0.446,
            "upc" : None,
            "quantity_available_for_games" : 80000,
            "sale_ends" : "2018-03-12 18:47:27",
            "spare_parts" : 0,
            "owner_sku" : None,
            "keywords" : "track, train, railroad, railway, acrylic, token, rail, transport, tramway",
            "price" : "0.2066",
            "has_extraimages" : 0,
            "interior_height" : 0,
            "date_created" : "2018-03-12 18:47:27",
            "original_price" : "0.2066",
            "departments" : [
               "parts"
            ],
            "last_price_change" : "2018-08-22 15:24:29",
            "photo_size" : "300x300",
            "sale_price" : 0,
            "quantity_available_for_shop" : 80000,
            "badge" : None,
            "sku_id" : "CFA21C14-2625-11E8-A307-B681E387AC3B",
            "price_10" : "0.1378",
            "price_100" : "0.1102",
            "use_insert_with_parts_boxes" : None,
            "on_sale" : 0,
            "owner_carton_label" : None,
            "box_insert" : 0,
            "use_insert_with_boxes" : None,
            "size_in_mm" : 0,
            "description" : "An acrylic piece of train track.",
            "date_updated" : "2023-09-29 23:28:40",
            "original_price_10" : "0.1378",
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/DA2B7C0E-26DC-11E8-94C8-8D83F6956076.png",
            "id" : "CF9BA320-2625-11E8-A307-B681E387AC3B",
            "units_per_carton" : 1,
            "family" : "Train Track",
            "supplies" : 0,
            "usable_in_games" : 1,
            "shop_uri" : "/parts/acrylic-train-track-green",
            "number_of_sides" : 0,
            "height" : 1.26,
            "discontinued" : 0,
            "public" : 1,
            "uri_part" : "acrylic-train-track-green",
            "virtual" : 0,
            "category" : "Tokens",
            "original_price_1000" : "0.0626",
            "weight" : 0.0326
         },
         {
            "box" : 0,
            "for_resale" : 1,
            "object_name" : "Part",
            "object_type" : "part",
            "quantity" : 149,
            "youtube_video_id" : "ImtUM7M0r2E",
            "name" : "Acrylic Train Track, Orange",
            "material" : "Plastic",
            "color" : "Orange",
            "low_volume" : 0,
            "made_on_demand" : 1,
            "date_published" : "2018-03-12 18:53:41",
            "original_price_100" : "0.1102",
            "is_3d_printed" : 0,
            "interior_depth" : 0,
            "vintage" : 0,
            "made_in_the_usa" : 1,
            "interior_width" : 0,
            "price_1000" : "0.0626",
            "has_extraimages" : 0,
            "price" : "0.2066",
            "keywords" : "track, train, railroad, railway, acrylic, token, rail, transport, tramway",
            "owner_sku" : None,
            "spare_parts" : 0,
            "quantity_available_for_games" : 80000,
            "sale_ends" : "2018-03-12 18:47:35",
            "upc" : None,
            "width" : 0.446,
            "depth" : 0.21,
            "sale_price" : 0,
            "photo_size" : "300x300",
            "departments" : [
               "parts"
            ],
            "last_price_change" : "2018-08-22 15:24:36",
            "interior_height" : 0,
            "date_created" : "2018-03-12 18:47:35",
            "original_price" : "0.2066",
            "use_insert_with_boxes" : None,
            "date_updated" : "2023-10-15 06:15:10",
            "original_price_10" : "0.1378",
            "description" : "An acrylic piece of train track.",
            "size_in_mm" : 0,
            "use_insert_with_parts_boxes" : None,
            "on_sale" : 0,
            "box_insert" : 0,
            "owner_carton_label" : None,
            "price_100" : "0.1102",
            "price_10" : "0.1378",
            "badge" : None,
            "sku_id" : "D4B5CF70-2625-11E8-A307-EFC1822BCEBA",
            "quantity_available_for_shop" : 80000,
            "number_of_sides" : 0,
            "shop_uri" : "/parts/acrylic-train-track-orange",
            "family" : "Train Track",
            "id" : "D4B0B4EA-2625-11E8-A307-EFC1822BCEBA",
            "units_per_carton" : 1,
            "usable_in_games" : 1,
            "supplies" : 0,
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/D9CAF638-26DA-11E8-8A4F-E686183AAE20.png",
            "original_price_1000" : "0.0626",
            "category" : "Tokens",
            "weight" : 0.0284,
            "public" : 1,
            "uri_part" : "acrylic-train-track-orange",
            "virtual" : 0,
            "height" : 1.26,
            "discontinued" : 0
         },
         {
            "virtual" : 0,
            "uri_part" : "acrylic-train-track-purple",
            "public" : 1,
            "discontinued" : 0,
            "height" : 1.26,
            "weight" : 0.0284,
            "original_price_1000" : "0.0626",
            "category" : "Tokens",
            "usable_in_games" : 1,
            "supplies" : 0,
            "family" : "Train Track",
            "units_per_carton" : 1,
            "id" : "D9536C54-2625-11E8-A307-F73ADE6D9724",
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/70003392-26DC-11E8-8A4F-D7A2BAF4D5EC.png",
            "number_of_sides" : 0,
            "shop_uri" : "/parts/acrylic-train-track-purple",
            "price_100" : "0.1102",
            "price_10" : "0.1378",
            "badge" : None,
            "sku_id" : "D956D600-2625-11E8-A307-F73ADE6D9724",
            "quantity_available_for_shop" : 80000,
            "date_updated" : "2023-10-19 21:50:35",
            "original_price_10" : "0.1378",
            "size_in_mm" : 0,
            "description" : "An acrylic piece of train track.",
            "use_insert_with_boxes" : None,
            "owner_carton_label" : None,
            "box_insert" : 0,
            "use_insert_with_parts_boxes" : None,
            "on_sale" : 0,
            "original_price" : "0.2066",
            "interior_height" : 0,
            "date_created" : "2018-03-12 18:47:43",
            "sale_price" : 0,
            "photo_size" : "300x300",
            "last_price_change" : "2018-08-22 15:24:46",
            "departments" : [
               "parts"
            ],
            "upc" : None,
            "width" : 0.446,
            "depth" : 0.21,
            "price" : "0.2066",
            "has_extraimages" : 0,
            "keywords" : "track, train, railroad, railway, acrylic, token, rail, transport, tramway",
            "owner_sku" : None,
            "spare_parts" : 0,
            "quantity_available_for_games" : 80000,
            "sale_ends" : "2018-03-12 18:47:43",
            "interior_width" : 0,
            "price_1000" : "0.0626",
            "date_published" : "2018-03-12 18:51:48",
            "original_price_100" : "0.1102",
            "vintage" : 0,
            "interior_depth" : 0,
            "made_in_the_usa" : 1,
            "is_3d_printed" : 0,
            "low_volume" : 0,
            "color" : "Purple",
            "made_on_demand" : 1,
            "name" : "Acrylic Train Track, Purple",
            "youtube_video_id" : "ImtUM7M0r2E",
            "material" : "Plastic",
            "object_name" : "Part",
            "object_type" : "part",
            "quantity" : 193,
            "box" : 0,
            "for_resale" : 1
         },
         {
            "photo_size" : "300x300",
            "sale_price" : 0,
            "last_price_change" : "2018-08-22 15:25:01",
            "departments" : [
               "parts"
            ],
            "original_price" : "0.2066",
            "date_created" : "2018-03-12 18:47:54",
            "interior_height" : 0,
            "description" : "An acrylic piece of train track.",
            "size_in_mm" : 0,
            "date_updated" : "2023-09-20 20:43:54",
            "original_price_10" : "0.1378",
            "use_insert_with_boxes" : None,
            "box_insert" : 0,
            "owner_carton_label" : None,
            "on_sale" : 0,
            "use_insert_with_parts_boxes" : None,
            "price_100" : "0.1102",
            "price_10" : "0.1378",
            "quantity_available_for_shop" : 80000,
            "badge" : None,
            "sku_id" : "DFCF656A-2625-11E8-8C8A-FBF218EC9918",
            "number_of_sides" : 0,
            "shop_uri" : "/parts/acrylic-train-track-red",
            "supplies" : 0,
            "usable_in_games" : 1,
            "units_per_carton" : 1,
            "id" : "DFCB8E04-2625-11E8-8C8A-FBF218EC9918",
            "family" : "Train Track",
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/8855AAAE-26DB-11E8-94C8-DCCBDC566D86.png",
            "weight" : 0.0294,
            "category" : "Tokens",
            "original_price_1000" : "0.0626",
            "virtual" : 0,
            "uri_part" : "acrylic-train-track-red",
            "public" : 1,
            "discontinued" : 0,
            "height" : 1.26,
            "box" : 0,
            "for_resale" : 1,
            "object_type" : "part",
            "object_name" : "Part",
            "quantity" : 279,
            "youtube_video_id" : "ImtUM7M0r2E",
            "name" : "Acrylic Train Track, Red",
            "material" : "Plastic",
            "low_volume" : 0,
            "color" : "Red",
            "made_on_demand" : 1,
            "original_price_100" : "0.1102",
            "date_published" : "2018-03-12 18:51:04",
            "interior_depth" : 0,
            "made_in_the_usa" : 1,
            "vintage" : 0,
            "is_3d_printed" : 0,
            "interior_width" : 0,
            "price_1000" : "0.0626",
            "keywords" : "track, train, railroad, railway, acrylic, token, rail, transport, tramway",
            "owner_sku" : None,
            "has_extraimages" : 0,
            "price" : "0.2066",
            "sale_ends" : "2018-03-12 18:47:54",
            "quantity_available_for_games" : 80000,
            "spare_parts" : 0,
            "width" : 0.446,
            "upc" : None,
            "depth" : 0.21
         },
         {
            "shop_uri" : "/parts/acrylic-train-track-white",
            "number_of_sides" : 0,
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/0DC46F16-217F-11E8-8B26-2EFA93A6FE1D.png",
            "units_per_carton" : 1,
            "id" : "CBFA5392-1CB1-11E8-BC59-BCF893A6FE1D",
            "family" : "Train Track",
            "supplies" : 0,
            "usable_in_games" : 1,
            "category" : "Tokens",
            "original_price_1000" : "0.0626",
            "weight" : 0.0314,
            "height" : 1.26,
            "discontinued" : 0,
            "uri_part" : "acrylic-train-track-white",
            "public" : 1,
            "virtual" : 0,
            "departments" : [
               "parts"
            ],
            "last_price_change" : "2018-08-22 15:25:10",
            "photo_size" : "300x300",
            "sale_price" : 0,
            "date_created" : "2018-02-28 18:04:19",
            "interior_height" : 0,
            "original_price" : "0.2066",
            "use_insert_with_parts_boxes" : None,
            "on_sale" : 0,
            "box_insert" : 0,
            "owner_carton_label" : None,
            "use_insert_with_boxes" : None,
            "size_in_mm" : 0,
            "description" : "An acrylic piece of train track.",
            "date_updated" : "2023-10-15 18:54:00",
            "original_price_10" : "0.1378",
            "quantity_available_for_shop" : 80000,
            "sku_id" : "CC049BB8-1CB1-11E8-BC59-BCF893A6FE1D",
            "badge" : None,
            "price_10" : "0.1378",
            "price_100" : "0.1102",
            "is_3d_printed" : 0,
            "interior_depth" : 0,
            "made_in_the_usa" : 1,
            "vintage" : 0,
            "original_price_100" : "0.1102",
            "date_published" : "2018-02-28 18:04:33",
            "price_1000" : "0.0626",
            "interior_width" : 0,
            "quantity_available_for_games" : 80000,
            "sale_ends" : "2018-02-28 18:04:19",
            "spare_parts" : 0,
            "keywords" : "track, train, railroad, railway, acrylic, token, rail, transport, tramway",
            "owner_sku" : None,
            "has_extraimages" : 0,
            "price" : "0.2066",
            "depth" : 0.21,
            "width" : 0.446,
            "upc" : None,
            "for_resale" : 1,
            "box" : 0,
            "quantity" : 166,
            "object_type" : "part",
            "object_name" : "Part",
            "material" : "Plastic",
            "youtube_video_id" : "ImtUM7M0r2E",
            "name" : "Acrylic Train Track, White",
            "made_on_demand" : 1,
            "color" : "White",
            "low_volume" : 0
         },
         {
            "number_of_sides" : 0,
            "shop_uri" : "/parts/acrylic-train-track-yellow",
            "usable_in_games" : 1,
            "supplies" : 0,
            "family" : "Train Track",
            "id" : "E44FAEB0-2625-11E8-A307-DF50651C5096",
            "units_per_carton" : 1,
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/5BA6D1F4-26DB-11E8-94C8-9FE3D04E63E6.png",
            "weight" : 0.0291,
            "original_price_1000" : "0.0626",
            "category" : "Tokens",
            "virtual" : 0,
            "public" : 1,
            "uri_part" : "acrylic-train-track-yellow",
            "discontinued" : 0,
            "height" : 1.26,
            "sale_price" : 0,
            "photo_size" : "300x300",
            "last_price_change" : "2018-08-22 15:25:17",
            "departments" : [
               "parts"
            ],
            "original_price" : "0.2066",
            "date_created" : "2018-03-12 18:48:02",
            "interior_height" : 0,
            "date_updated" : "2023-10-16 03:01:59",
            "original_price_10" : "0.1378",
            "size_in_mm" : 0,
            "description" : "An acrylic piece of train track.",
            "use_insert_with_boxes" : None,
            "owner_carton_label" : None,
            "box_insert" : 0,
            "on_sale" : 0,
            "use_insert_with_parts_boxes" : None,
            "price_100" : "0.1102",
            "price_10" : "0.1378",
            "badge" : None,
            "sku_id" : "E4568AC8-2625-11E8-A307-DF50651C5096",
            "quantity_available_for_shop" : 80000,
            "date_published" : "2018-03-12 18:50:25",
            "original_price_100" : "0.1102",
            "interior_depth" : 0,
            "vintage" : 0,
            "made_in_the_usa" : 1,
            "is_3d_printed" : 0,
            "interior_width" : 0,
            "price_1000" : "0.0626",
            "has_extraimages" : 0,
            "price" : "0.2066",
            "owner_sku" : None,
            "keywords" : "track, train, railroad, railway, acrylic, token, rail, transport, tramway",
            "spare_parts" : 0,
            "sale_ends" : "2018-03-12 18:48:02",
            "quantity_available_for_games" : 80000,
            "upc" : None,
            "width" : 0.446,
            "depth" : 0.21,
            "box" : 0,
            "for_resale" : 1,
            "object_name" : "Part",
            "object_type" : "part",
            "quantity" : 311,
            "name" : "Acrylic Train Track, Yellow",
            "youtube_video_id" : "ImtUM7M0r2E",
            "material" : "Plastic",
            "low_volume" : 0,
            "color" : "Yellow",
            "made_on_demand" : 1
         },
         {
            "upc" : None,
            "width" : 1.05,
            "depth" : 0.21,
            "has_extraimages" : 0,
            "price" : "0.2629",
            "keywords" : "acrylic, train, boxcar, box, freight, car, railroad, transport, covered goods wagon, goods wagon, goods van, louvre van, van, cargo, container, bulk",
            "owner_sku" : None,
            "spare_parts" : 0,
            "quantity_available_for_games" : 80000,
            "sale_ends" : "2018-03-05 16:43:09",
            "interior_width" : 0,
            "price_1000" : "0.0907",
            "date_published" : "2018-03-05 16:43:27",
            "original_price_100" : "0.1478",
            "interior_depth" : 0,
            "made_in_the_usa" : 1,
            "vintage" : 0,
            "is_3d_printed" : 0,
            "low_volume" : 0,
            "color" : "Black",
            "made_on_demand" : 1,
            "youtube_video_id" : "lhfmcx80yok",
            "name" : "Acrylic Train, Box Car, Black",
            "material" : "Plastic",
            "object_name" : "Part",
            "object_type" : "part",
            "quantity" : 154,
            "box" : 0,
            "for_resale" : 1,
            "virtual" : 0,
            "public" : 1,
            "uri_part" : "acrylic-train-box-car-black",
            "discontinued" : 0,
            "height" : 0.47,
            "weight" : 0.064,
            "original_price_1000" : "0.0907",
            "category" : "Vehicles",
            "usable_in_games" : 1,
            "supplies" : 0,
            "family" : "Train Box Car",
            "units_per_carton" : 1,
            "id" : "499A1F22-2094-11E8-8656-7EFE93A6FE1D",
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/0A6A4C44-20CD-11E8-84FA-82EF93A6FE1D.png",
            "number_of_sides" : 0,
            "shop_uri" : "/parts/acrylic-train-box-car-black",
            "price_10" : "0.1847",
            "price_100" : "0.1478",
            "sku_id" : "499C7B46-2094-11E8-8656-7EFE93A6FE1D",
            "badge" : None,
            "quantity_available_for_shop" : 80000,
            "date_updated" : "2023-10-17 09:25:14",
            "original_price_10" : "0.1847",
            "description" : "An acrylic train box car.  It comes in 8 colors.",
            "size_in_mm" : 0,
            "use_insert_with_boxes" : None,
            "owner_carton_label" : None,
            "box_insert" : 0,
            "use_insert_with_parts_boxes" : None,
            "on_sale" : 0,
            "original_price" : "0.2629",
            "date_created" : "2018-03-05 16:43:09",
            "interior_height" : 0,
            "sale_price" : 0,
            "photo_size" : "300x300",
            "last_price_change" : "2018-03-08 16:41:04",
            "departments" : [
               "parts"
            ]
         },
         {
            "date_created" : "2018-03-05 16:43:42",
            "interior_height" : 0,
            "original_price" : "0.2629",
            "departments" : [
               "parts"
            ],
            "last_price_change" : "2018-03-08 16:42:21",
            "photo_size" : "300x300",
            "sale_price" : 0,
            "quantity_available_for_shop" : 80000,
            "sku_id" : "5CF9A7CC-2094-11E8-955A-190494A6FE1D",
            "badge" : None,
            "price_10" : "0.1847",
            "price_100" : "0.1478",
            "on_sale" : 0,
            "use_insert_with_parts_boxes" : None,
            "box_insert" : 0,
            "owner_carton_label" : None,
            "use_insert_with_boxes" : None,
            "size_in_mm" : 0,
            "description" : "An acrylic train box car.  It comes in 8 colors.",
            "original_price_10" : "0.1847",
            "date_updated" : "2023-10-03 04:40:29",
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/1E1EE484-20CD-11E8-84FA-9DEF93A6FE1D.png",
            "units_per_carton" : 1,
            "id" : "5CF6F95A-2094-11E8-955A-190494A6FE1D",
            "family" : "Train Box Car",
            "supplies" : 0,
            "usable_in_games" : 1,
            "shop_uri" : "/parts/acrylic-train-box-car-blue",
            "number_of_sides" : 0,
            "height" : 0.47,
            "discontinued" : 0,
            "public" : 1,
            "uri_part" : "acrylic-train-box-car-blue",
            "virtual" : 0,
            "category" : "Vehicles",
            "original_price_1000" : "0.0907",
            "weight" : 0.0625,
            "quantity" : 250,
            "object_type" : "part",
            "object_name" : "Part",
            "for_resale" : 1,
            "box" : 0,
            "made_on_demand" : 1,
            "color" : "Blue",
            "low_volume" : 0,
            "material" : "Plastic",
            "youtube_video_id" : "lhfmcx80yok",
            "name" : "Acrylic Train, Box Car, Blue",
            "price_1000" : "0.0907",
            "interior_width" : 0,
            "is_3d_printed" : 0,
            "interior_depth" : 0,
            "made_in_the_usa" : 1,
            "vintage" : 0,
            "original_price_100" : "0.1478",
            "date_published" : "2018-03-05 16:43:52",
            "depth" : 0.21,
            "width" : 1.05,
            "upc" : None,
            "quantity_available_for_games" : 80000,
            "sale_ends" : "2018-03-05 16:43:42",
            "spare_parts" : 0,
            "keywords" : "acrylic, train, boxcar, box, freight, car, railroad, transport, covered goods wagon, goods wagon, goods van, louvre van, van, cargo, container, bulk",
            "owner_sku" : None,
            "has_extraimages" : 0,
            "price" : "0.2629"
         },
         {
            "last_price_change" : "2018-03-08 17:49:05",
            "departments" : [
               "parts"
            ],
            "sale_price" : 0,
            "photo_size" : "300x300",
            "original_price" : "0.2629",
            "date_created" : "2018-03-05 16:44:12",
            "interior_height" : 0,
            "box_insert" : 0,
            "owner_carton_label" : None,
            "use_insert_with_parts_boxes" : None,
            "on_sale" : 0,
            "date_updated" : "2023-10-13 10:09:45",
            "original_price_10" : "0.1847",
            "description" : "An acrylic train box car.  It comes in 8 colors.",
            "size_in_mm" : 0,
            "use_insert_with_boxes" : None,
            "badge" : None,
            "sku_id" : "6F1B81FA-2094-11E8-955A-4C0494A6FE1D",
            "quantity_available_for_shop" : 80000,
            "price_10" : "0.1847",
            "price_100" : "0.1478",
            "shop_uri" : "/parts/acrylic-train-box-car-green",
            "number_of_sides" : 0,
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/3DDDCBBE-20CD-11E8-84FA-DBEF93A6FE1D.png",
            "usable_in_games" : 1,
            "supplies" : 0,
            "family" : "Train Box Car",
            "id" : "6F0FB488-2094-11E8-955A-4C0494A6FE1D",
            "units_per_carton" : 1,
            "weight" : 0.065,
            "original_price_1000" : "0.0907",
            "category" : "Vehicles",
            "discontinued" : 0,
            "height" : 0.47,
            "virtual" : 0,
            "uri_part" : "acrylic-train-box-car-green",
            "public" : 1,
            "for_resale" : 1,
            "box" : 0,
            "quantity" : 243,
            "object_name" : "Part",
            "object_type" : "part",
            "material" : "Plastic",
            "youtube_video_id" : "lhfmcx80yok",
            "name" : "Acrylic Train, Box Car, Green",
            "made_on_demand" : 1,
            "low_volume" : 0,
            "color" : "Green",
            "interior_depth" : 0,
            "made_in_the_usa" : 1,
            "vintage" : 0,
            "is_3d_printed" : 0,
            "date_published" : "2018-03-05 16:44:19",
            "original_price_100" : "0.1478",
            "price_1000" : "0.0907",
            "interior_width" : 0,
            "spare_parts" : 0,
            "sale_ends" : "2018-03-05 16:44:12",
            "quantity_available_for_games" : 80000,
            "has_extraimages" : 0,
            "price" : "0.2629",
            "keywords" : "acrylic, train, boxcar, box, freight, car, railroad, transport, covered goods wagon, goods wagon, goods van, louvre van, van, cargo, container, bulk",
            "owner_sku" : None,
            "depth" : 0.21,
            "upc" : None,
            "width" : 1.05
         },
         {
            "public" : 1,
            "uri_part" : "acrylic-train-box-car-orange",
            "virtual" : 0,
            "height" : 0.47,
            "discontinued" : 0,
            "category" : "Vehicles",
            "original_price_1000" : "0.0907",
            "weight" : 0.0654,
            "units_per_carton" : 1,
            "id" : "8091EF5A-2094-11E8-955A-500494A6FE1D",
            "family" : "Train Box Car",
            "supplies" : 0,
            "usable_in_games" : 1,
            "preview_uri" : "//s3.amazonaws.com/preview.thegamecrafter.com/48E54B68-20CD-11E8-A86F-8EE793A6FE1D.png",
            "number_of_sides" : 0,
            "shop_uri" : "/parts/acrylic-train-box-car-orange",
            "price_10" : "0.1847",
            "price_100" : "0.1478",
            "quantity_available_for_shop" : 80000,
            "sku_id" : "8094A3B2-2094-11E8-955A-500494A6FE1D",
            "badge" : None,
            "use_insert_with_boxes" : None,
            "description" : "An acrylic train box car.  It comes in 8 colors.",
            "size_in_mm" : 0,
            "date_updated" : "2023-10-22 12:07:48",
            "original_price_10" : "0.1847",
            "on_sale" : 0,
            "use_insert_with_parts_boxes" : None,
            "box_insert" : 0,
            "owner_carton_label" : None,
            "interior_height" : 0,
            "date_created" : "2018-03-05 16:44:41",
            "original_price" : "0.2629",
            "photo_size" : "300x300",
            "sale_price" : 0,
            "departments" : [
               "parts"
            ],
            "last_price_change" : "2018-03-08 17:50:40",
            "width" : 1.05,
            "upc" : None,
            "depth" : 0.21,
            "keywords" : "acrylic, train, boxcar, box, freight, car, railroad, transport, covered goods wagon, goods wagon, goods van, louvre van, van, cargo, container, bulk",
            "owner_sku" : None,
            "has_extraimages" : 0,
            "price" : "0.2629",
            "quantity_available_for_games" : 80000,
            "sale_ends" : "2018-03-05 16:44:41",
            "spare_parts" : 0,
            "interior_width" : 0,
            "price_1000" : "0.0907",
            "original_price_100" : "0.1478",
            "date_published" : "2018-03-05 16:45:00",
            "is_3d_printed" : 0,
            "made_in_the_usa" : 1,
            "interior_depth" : 0,
            "vintage" : 0,
            "color" : "Orange",
            "low_volume" : 0,
            "made_on_demand" : 1,
            "youtube_video_id" : "lhfmcx80yok",
            "name" : "Acrylic Train, Box Car, Orange",
            "material" : "Plastic",
            "object_type" : "part",
            "object_name" : "Part",
            "quantity" : 305,
            "box" : 0,
            "for_resale" : 1
         }
      ]
   }
}